#pragma once
#ifndef CNETS_H
#define CNETS_H

#ifndef SNET_H
#include "sNet.h"
#endif

class s_CNets {/*cluster of nets that read from the same geometric location
				  the geometric location is where the eye is rooted
				  the nets each find a specific pattern they are programed for, the number of pats the nets find is the number of nets
				  each net typically has it's hanging nodes root on multiple plates*/
public:
	s_CNets();
	~s_CNets();
	virtual unsigned char init(int nNets);/*initializes the net array does not fill pointers or own anything*/
	virtual unsigned char init(const s_CNets& other);/*assumes that if pointers to nets(but not eye) are non-null the objects are owned and should be copied to owned objects*/
	unsigned char newNets();/*create the nets but don't init*/
	void          delNets();
	virtual void          release();/*assumes that if the net pointers are non-null they are owned by this object (does not assuem ownership of eye)*/
	inline s_Net* get(int i_net) { return net[i_net]; }
	inline s_HexEye* getEye() { return eye; }
	s_Net** net;/*considered owned if non-null when released*/
	s_HexEye* eye;/*not considered owned by this object but may be owned in some iherited classes*/
	int N;/* number of nets actually pointing to something */

	s_nNode* trigger_node;/*this node is setup to link to all the lowest plates,
						   if the plates do not pass the threshold value
						   of this node this net cluster will not try to root the eye or seed
						   considered owned if non-null when released*/
protected:
	int N_mem;
};


namespace n_CNets {
	bool runNNet(s_CNets* nets, s_HexPlate* plate, long plate_index);/*roots and runs the nnet at plate_index*/
	bool runNNet(s_CNets* nets, s_HexPlateLayer* plates, long plate_index);/*roots and runs the nnets on the plates at the plate index
																				all plates are assumed to have the same dimensions*/

																				/****helpers to runNNet****/
	inline bool rootOnPlate(s_CNets* nets, s_HexPlate* plate, long plate_index);/*roots the eye and then the nets at the plate index*/
	inline bool rootOnPlates(s_CNets* nets, s_HexPlateLayer* plates, long plate_index); /*roots eyes with hanging nodes pointing to multiple plates*/
	/*helpers to rootOnPlate*/
	inline bool rootEye(s_CNets* nets, s_HexPlate* basePlate, long plate_index);/*eye should be the same object for the cluster nets and each net in
																						the cluster */
	void rootNetsOnPlate(s_CNets* nets, s_HexPlate* plate);/*assumes the eye has already been rooted at correct position but
															not necessarily , also assumes that the s_hexEye pointer in the
																nets is the same as the s_hexEye pointer in the s_CNets
																roots each hex of the lowest layer of the net so that it
																matches the position of the lowest layer of they eye
																the rooting is done with the hanging nodes,
																only uses 1 hanging node */
																/*helpers to rootOnPlates */
	void rootNetsOnPlates(s_CNets* nets, s_HexPlateLayer* plates);/*same as root Nets on plate but does it for multiple plates*/


}
class CNets : public Base {/*class that generates the cluster nets*/
public:
	CNets();
	~CNets();
	unsigned char init(HexEye* eye, int nNets, int nLev, int numLevNodes[], int numHanging);/* nNets is the number of nets in the spawned s_CNets
																initiates each sNet so tha it will generate a certain kind of s_Net struct
																nLev is the number of levels in the s_Net
																numLevelNodes is an array of len nLev giving the number of nodes in each level
																numHanging is the number of open node pointers 'hanging' from each
																node in the bottom level */
	unsigned char init(int nNets, HexEye* eye, int numHanging = 1);  /*initializes nets to have same structure as eye
														   with number of hanging nodes equal to the number of plates*/
	void release();

	unsigned char spawnFullConn(s_CNets* cn, s_HexEye* eye);/*spawns a fully connected net, the s_HexEye should have been generated by
															the HexEye the eye generator used in the init of this sNet
															the hex of the nnet for the top and the bottom point to the corresponding eye hexes
															the number of nodes for each layer of  the nnet is as specified by init and should be the
															same as the number of nodes in each layer of the eye
															each bottom node of the snet is connected to one hex of the bottom layer of the eye*/
	unsigned char spawn(s_CNets* cn, s_HexEye* eye);  /*this eye should have exactly the same structure as the eye used to initialize the sNet
													  the net should have the same structure as the eye, (web however is not currently connected)
													  Each node in the net links down to 7 nodes in the net layer beneath it (except for the bottom)
													  The hex of each node is the corresponding eye hex
													  For all levels: eye num hexes = num of net nodes
													  hanging nodes from lowest net level are set in the init */
	unsigned char spawn(s_CNets* cn);/*just spawns the nets but does nothing with the eye during spawn*/
	void          despawn(s_CNets* sn);

	inline int getNumNets() { return m_nNets; }
	inline int getTotalNumWs_perNet() { return m_genNet->getTotalNumWs(); }
	inline int getTotalNumNodes_perNet() { return m_genNet->getTotalNumNodes(); }
	inline int getTotalNumBottomOs_perNet() { return m_genNet->getTotalNumBottomNodes(); }
	inline int getNumLevels_perNet() { return m_genNet->getNumLevels(); }
	inline int* getNumLevNodes_perNet() { return m_genNet->getNumLevNodesPtr(); }
	inline int getTotalNumWBs_perNet() { return m_genNet->getTotalNumWBs(); }

	inline sNet* getNetGen() { return m_genNet; }

protected:
	/*not owned*/
	HexEye* m_genHexEye;
	/*owned*/
	sNet* m_genNet;
	int   m_nNets;
};

#endif