#pragma once
#ifndef TRAINL0STAMP_H
#define TRAINL0STAMP_H

#ifndef L0LAYER_H
#include "../NNet/L0Layer.h"
#endif
#ifndef COLOR_H
#include "../HexedImg/Color.h"
#endif
#ifndef LUNALAYER_H
#include "../Luna/LunaLayer.h"
#endif
#ifndef PARSETXT_H
#include "../FileIO/ParseTxt.h"
#endif
#ifndef CTARGAIMAGE_H
#include "../FileIO/CTargaImage.h"
#endif

#define TRAINL0STAMP_BASEDIR "Dat"
#define TRAINL0STAMP_L0DIR "L0"
#define TRAINL0STAMP_SIGDIR "Sig"
#define TRAINL0STAMP_BAKDIR "Bak"
#define TRAINL0STAMP_STAMPDIR "Stamp"

#define TRAINL0STAMP_IMGFILE "imgf"
#define TRAINL0STAMP_KEYFILE "keys"
#define TRAINL0STAMP_MASTERKEYFILE "masterKey"
#define TRAINL0STAMP_IMGFILESUF ".tga"
#define TRAINL0STAMP_KEYFILESUF ".txt"

#define TRAINL0STAMP_L0TRAINKEY "L0TrainKey" /*first line: numLevels, num nds, num nds...  second line: dummy wbs*/
#define TRAINL0STAMP_L0BASEOFILE "NetBaseO" /* entire o array for all nodes in the net first level is dumped=1 node then next and next...*/
#define TRAINL0STAMP_L0BASEOFILESUF ".txt"

/*used to read output of Tensor Flow training*/
#define TRAINL0STAMP_L0KEYFILE "L0Key" /* r, len_wbs = len of net, num_stamps = number of nets*/
#define TRAINL0STAMP_L0NETS "L0Nets" /*trained nnet wbs chains, one net per line up to total number of nets (uses BASOFILESUF) resides in the L0DIR*/

#define TRAINL0STAMP_INTSTRLEN 5

const int TRAINL0STAMP_num_img_eye_lev = 4;

/*key file generated by this class contains: number of levels [len 1], list of number of nodes(os) per level [len number of levels]*/

class TrainL0Stamp : public Base {
public:
	TrainL0Stamp();
	~TrainL0Stamp();

	unsigned char init(
		Img* baseImg,
		float r /*must be the same r as was used for the training images*/
		);
	void release();
	int getOs_len();
	int getNumBottomOs();
	int getNumLevels();
	unsigned char getNumNodesPerLevel(float levNodes[], int numLev);
	unsigned char runDir(std::string& stampDir);

protected:
	s_2pt_i m_eye_center;
	
	/*not owned*/
	Img* m_baseImg;
	/*owned*/
	CTargaImage* m_tga;
	s_datLine* m_net_lines;/*scratch lines written and overwritten*/
	float* m_net_os_scratch;
	/**generators**/
	HexEye* m_genHexEye;
	HexEyeImg* m_genHexedImg;
	Col* m_genColLayer;
	LunaLayer* m_genLunaLayer;
	L0Net* m_genL0Net;

	/**data objects**/
	s_HexEye* m_seye;
	s_ColPlateLayer* m_colPlates;
	s_HexPlateLayer* m_lunaPlates;
	s_CNets* m_L0Nets;

	s_ColWheel m_sCol;

	unsigned char genWhiteColWheel();
	unsigned char runImg(Img* baseImg, float net_os[]);



	bool ErrHandle(unsigned char ecode, const char* errstr);
};

#endif